### ISSUE TITLE
Seed generation error: "Failed to generate Z17R seed D:"

### ISSUE THREAD

**Issue by Memesland-code** [rickfay/z17-randomizer#11]
Hello,
Since a few hours I'm trying to generate a seed to play Zelda ALBW rando with your tool but got that error:
"Failed to generate Z17R seed D:"

All details of what I did:

- First here's a screen of the folder
![folder](https://user-images.githubusercontent.com/58827868/202234672-0ebdae2f-b86f-4a9f-913c-9b9a141978e0.png)

Then I've tried the 2 ways to generate a seed:

- 1st executing the randomizer.exe
What I do and get at the end

![seed_gen_part1](https://user-images.githubusercontent.com/58827868/202234989-028a2476-aa84-4756-8085-4395595c23fd.png)
![seed_gen_part2](https://user-images.githubusercontent.com/58827868/202235000-4768ffd1-3853-4a28-a9d7-2d249e81dfa3.png)

By the way I haven't touched the **config.toml** file.
Content:
```
rom = 'A Link Between Worlds (USA).3ds'
output = 'generated'
```

- 2nd thing I tried, is to run the .exe with a preset file which gives me this indication at the end
![seed_gen_with_preset](https://user-images.githubusercontent.com/58827868/202237914-2a4d753d-808f-4f44-9d4b-336136669b7d.png)

So I don't know what I'm doing wrong. I have also checked the game id but it's the same as in the readme (00040000000EC300)
I think that's all I need to mention, please tell me if you need more information.
Hope somebody will be able to help me!

**Comment by rickfay** [comment]
This will typically happen if there's an issue with your ROM.

Your ROM must be:
1. A North American copy of A Link Between Worlds
2. Decrypted

Instructions to rip and decrypt a legal copy of your game can be found [here](https://citra-emu.org/wiki/dumping-game-cartridges/).

If your ROM is a `.CIA` that needs to be converted to `.3DS` you can use [this tool](https://github.com/davFaithid/CIA-to-3DS-Rom-Converter/releases/tag/1.0).
