### ISSUE TITLE
Language breaks the patch

### ISSUE THREAD

**Issue by loicfrance** [rickfay/z17-randomizer#40]
At least on 3ds hardware, Having another language than English as the console language makes the patch not working completely as intended (e.g, objects not at their expected locations, Cucco game not unlocked to the rooster level, minigames not giving the right reward, etc).
The hints are consistent with the actual objects in-game.

**Comment by rickfay** [comment]
This is correct. The randomizer does not support non-English languages at this time.

**Comment by guigui0246** [comment]
You should add this info to the README because I had this problem and I know someone else that had this problem.
