### ISSUE TITLE
Master Sword weakened when upgrading + Hinox not randomized ingame but is in the spoiler

### ISSUE THREAD

**Issue by FireDroX** [rickfay/z17-randomizer#71]
I don’t know if anyone already said that but,
If you have the last upgrade (yellow one) of the Master Sword and you go upgrade it at the Hyrule Blacksmith, he will give you the first upgrade (the red one) and you will just loose your upgrade.

EDIT : 
In my spoiler log I got an Hinox like that but it was vanilla ingame
        "Hinox (1)":                                     "Lost Maiamai",
        "Hinox (2)":                                     "Lost Maiamai",
        "Hinox (3)":                                     "Master Ore",
        "Hinox (4)":                                     "Silver Rupee",
        "Hinox (5)":                                     "Purple Rupee",
        "Hinox (6)":                                     "Zora's Flippers",
Maybe it is because of I don't really know
      "randomize_dungeon_prizes": false,

**Comment by rickfay** [comment]
Did you set your system language to English? Not doing so can cause NPCs (among other checks) to give you the wrong items, and just generally not work correctly.
